version: '3'
services:
  opensearch-node1:
    image: opensearchstaging/opensearch:3.2.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Sets the name of the OpenSearch cluster
      - node.name=opensearch-node1 # Sets the name of the node in the cluster
      - discovery.seed_hosts=opensearch-node1,opensearch-node2 # Defines initial nodes for cluster discovery
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2 # Defines initial cluster manager nodes
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyPassword123! # Sets the initial admin password
      - http.type=reactor-netty4
      - opensearch.experimental.feature.transport.stream.enabled=true
#      - opensearch.experimental.feature.arrow.streams.enabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Dio.netty.allocator.numDirectArenas=1 -Dio.netty.noUnsafe=false -Dio.netty.tryUnsafe=true -Dio.netty.tryReflectionSetAccessible=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
#      - transport.stream.type.default=FLIGHT-SECURE
#      - flight.ssl.enable=true
#      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Sets JVM heap size to 512MB
#      - "OPENSEARCH_JAVA_OPTS+=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      - "DISABLE_SECURITY_PLUGIN=true"
#      - arrow.flight.publish_port=9401
#      - network.host=0.0.0.0
      - arrow.flight.publish_host=opensearch-node1
      - arrow.flight.bind_host=opensearch-node1
      - http.netty.max_composite_buffer_components=2
#      - arrow.flight.publish_host=172.18.0.3
#      - arrow.flight.bind_host=172.18.0.3

    ulimits:
      memlock:
        soft: -1 # Ensures unlimited memory locking
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      # Persist data for the first OpenSearch node to ensure cluster state, indexes, and metadata are retained
      - opensearch-data1:/usr/share/opensearch/data

      # Mount the local plugin build directory into the container to make custom plugins available for installation
      - /Volumes/workplace/ml-commons/plugin/build/distributions/:/usr/share/opensearch/ml-plugin
      - /Volumes/workplace/OpenSearch/plugins/transport-reactor-netty4/build/distributions/:/usr/share/opensearch/transport-plugin
      - /Volumes/workplace/OpenSearch/plugins/arrow-flight-rpc/build/distributions/:/usr/share/opensearch/arrow-plugin

    command: >
      bash -c "
        echo 'Listing ML plugin directory:';
        ls -la /usr/share/opensearch/ml-plugin/;

        echo 'Removing old plugins...';
        bin/opensearch-plugin remove opensearch-skills || true;
        bin/opensearch-plugin remove opensearch-ml || true;
      
        echo 'Installing ML plugin...';
        bin/opensearch-plugin install --batch --verbose file:///usr/share/opensearch/ml-plugin/opensearch-ml-3.2.0.0-SNAPSHOT.zip;
        
        echo 'Installing transport plugin...';
        bin/opensearch-plugin install --batch --verbose file:///usr/share/opensearch/transport-plugin/transport-reactor-netty4-3.2.0-SNAPSHOT.zip;
        
        echo 'Installing arrow plugin...';
        bin/opensearch-plugin install --batch --verbose file:///usr/share/opensearch/arrow-plugin/arrow-flight-rpc-3.2.0-SNAPSHOT.zip;
      
        echo 'Listing installed plugins:';
        ls -la /usr/share/opensearch/plugins/;

        ./opensearch-docker-entrypoint.sh opensearch
      "
    ports:
      - 9200:9200 # Main OpenSearch API port
      - 9600:9600 # required for Performance Analyzer
      - 5005:5005 # Debugging port

    networks:
      - opensearch-net # Connects to OpenSearch network

  opensearch-node2:
    image: opensearchstaging/opensearch:3.2.0
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyPassword123!
      - http.type=reactor-netty4
      - opensearch.experimental.feature.transport.stream.enabled=true
#      - opensearch.experimental.feature.arrow.streams.enabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Dio.netty.allocator.numDirectArenas=1 -Dio.netty.noUnsafe=false -Dio.netty.tryUnsafe=true -Dio.netty.tryReflectionSetAccessible=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007
#      - transport.stream.type.default=FLIGHT-SECURE
#      - flight.ssl.enable=true
#      - "OPENSEARCH_JAVA_OPTS+=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      - "DISABLE_SECURITY_PLUGIN=true"
#      - arrow.flight.publish_port=9400
      - network.host=0.0.0.0
      - arrow.flight.publish_host=opensearch-node2
      - arrow.flight.bind_host=opensearch-node2
      - http.netty.max_composite_buffer_components=2
#      - arrow.flight.publish_host=172.18.0.2
#      - arrow.flight.bind_host=172.18.0.2

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      # Persist data for the second OpenSearch node to maintain high availability and redundancy
      - opensearch-data2:/usr/share/opensearch/data

      # Mount the local plugin build directory into the container to make custom plugins available for installation
      - /Volumes/workplace/ml-commons/plugin/build/distributions/:/usr/share/opensearch/ml-plugin
      - /Volumes/workplace/OpenSearch/plugins/transport-reactor-netty4/build/distributions/:/usr/share/opensearch/transport-plugin
      - /Volumes/workplace/OpenSearch/plugins/arrow-flight-rpc/build/distributions/:/usr/share/opensearch/arrow-plugin

    command: >
      bash -c "
        echo 'Listing ML plugin directory:';
        ls -la /usr/share/opensearch/ml-plugin/;

        echo 'Removing old plugins...';
        bin/opensearch-plugin remove opensearch-skills || true;
        bin/opensearch-plugin remove opensearch-ml || true;

        echo 'Installing ML plugin...';
        bin/opensearch-plugin install --batch --verbose file:///usr/share/opensearch/ml-plugin/opensearch-ml-3.2.0.0-SNAPSHOT.zip;

        echo 'Installing transport plugin...';
        bin/opensearch-plugin install --batch --verbose file:///usr/share/opensearch/transport-plugin/transport-reactor-netty4-3.2.0-SNAPSHOT.zip;

        echo 'Installing arrow plugin...';
        bin/opensearch-plugin install --batch --verbose file:///usr/share/opensearch/arrow-plugin/arrow-flight-rpc-3.2.0-SNAPSHOT.zip;

        echo 'Listing installed plugins:';
        ls -la /usr/share/opensearch/plugins/;

        ./opensearch-docker-entrypoint.sh opensearch
      "
    networks:
      - opensearch-net

    ports:
      - 5007:5007

#  opensearch-ml1:
#    image: opensearchstaging/opensearch:3.2.0
#    container_name: opensearch-ml1
#    environment:
#      - cluster.name=opensearch-cluster
#      - node.name=opensearch-ml1
#      - node.roles=ml # Defines this node as an ML node
#      - discovery.seed_hosts=opensearch-node1,opensearch-node2
#      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
#      - bootstrap.memory_lock=true
#      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
#      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyPassword123!
#      - http.type=reactor-netty4
##      - opensearch.experimental.feature.transport.stream.enabled=true
##      - "OPENSEARCH_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
#      - "DISABLE_SECURITY_PLUGIN=true"
#
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    volumes:
#      # Persist machine learning-related data for the first ML node to store model metadata and results
#      - opensearch-ml1:/usr/share/opensearch/data
#
#      # Mount the local plugin build directory into the container to make custom plugins available for installation
#      - /Volumes/workplace/ml-commons/plugin/build/distributions/:/usr/share/opensearch/ml-plugin
#      - /Volumes/workplace/OpenSearch/plugins/transport-reactor-netty4/build/distributions/:/usr/share/opensearch/transport-plugin
#
#    command: >
#      bash -c "
#        echo 'Listing ML plugin directory:';
#        ls -la /usr/share/opensearch/ml-plugin/;
#
#        echo 'Removing old plugins...';
#        bin/opensearch-plugin remove opensearch-skills || true;
#        bin/opensearch-plugin remove opensearch-ml || true;
#
#        echo 'Installing ML plugin...';
#        bin/opensearch-plugin install --batch --verbose file:///usr/share/opensearch/ml-plugin/opensearch-ml-3.2.0.0-SNAPSHOT.zip;
#
#        echo 'Installing transport plugin...';
#        bin/opensearch-plugin install --batch --verbose file:///usr/share/opensearch/transport-plugin/transport-reactor-netty4-3.2.0-SNAPSHOT.zip;
#
#        echo 'Listing installed plugins:';
#        ls -la /usr/share/opensearch/plugins/;
#
#        ./opensearch-docker-entrypoint.sh opensearch
#      "
#    networks:
#      - opensearch-net
#
#  opensearch-ml2:
#    image: opensearchstaging/opensearch:3.2.0
#    container_name: opensearch-ml2
#    environment:
#      - cluster.name=opensearch-cluster
#      - node.name=opensearch-ml2
#      - node.roles=ml
#      - discovery.seed_hosts=opensearch-node1,opensearch-node2
#      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
#      - bootstrap.memory_lock=true
#      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
#      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyPassword123!
#      - http.type=reactor-netty4
##      - opensearch.experimental.feature.transport.stream.enabled=true
##      - "OPENSEARCH_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
#      - "DISABLE_SECURITY_PLUGIN=true"
#
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    volumes:
#      # Persist machine learning-related data for the second ML node to support distributed ML processing and data redundancy
#      - opensearch-ml2:/usr/share/opensearch/data
#
#      # Mount the local plugin build directory into the container to make custom plugins available for installation
#      - /Volumes/workplace/ml-commons/plugin/build/distributions/:/usr/share/opensearch/ml-plugin
#      - /Volumes/workplace/OpenSearch/plugins/transport-reactor-netty4/build/distributions/:/usr/share/opensearch/transport-plugin
#
#    command: >
#      bash -c "
#        echo 'Listing ML plugin directory:';
#        ls -la /usr/share/opensearch/ml-plugin/;
#
#        echo 'Removing old plugins...';
#        bin/opensearch-plugin remove opensearch-skills || true;
#        bin/opensearch-plugin remove opensearch-ml || true;
#
#        echo 'Installing ML plugin...';
#        bin/opensearch-plugin install --batch --verbose file:///usr/share/opensearch/ml-plugin/opensearch-ml-3.2.0.0-SNAPSHOT.zip;
#
#        echo 'Installing transport plugin...';
#        bin/opensearch-plugin install --batch --verbose file:///usr/share/opensearch/transport-plugin/transport-reactor-netty4-3.2.0-SNAPSHOT.zip;
#
#        echo 'Listing installed plugins:';
#        ls -la /usr/share/opensearch/plugins/;
#
#        ./opensearch-docker-entrypoint.sh opensearch
#      "
#    networks:
#      - opensearch-net

#  opensearch-dashboards:
#    image: opensearchproject/opensearch-dashboards:3.1.0
#    container_name: opensearch-dashboards
#    ports:
#      - 5601:5601
#    expose:
#      - "5601"
#    environment:
#      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
#    networks:
#      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:
#  opensearch-ml1:
#  opensearch-ml2:


networks:
  opensearch-net: